# Generated by Django 2.0.13 on 2019-04-13 21:17

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpBrClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('on_trial', models.BooleanField(default=False)),
                ('trial_finish', models.DateField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('google_analytics', models.CharField(blank=True, default='UA-49883581-3', max_length=50, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('exibiu_msg', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
