# Generated by Django 2.0.13 on 2019-04-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dthr_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora Cadastro')),
                ('texto', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('notify_url', models.CharField(max_length=255, verbose_name='URL')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
