# Generated by Django 2.0.13 on 2019-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='notify_icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='notify_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
